### ISSUE TITLE
Support Ubuntu Bionic

### ISSUE THREAD

**Issue by murphm8** [colcon/colcon-bundle#3]
Currently, only Ubuntu Xenial is supported. The sources the apt installer uses points to Xenial endpoints. We will have to introspect on which distribution of Ubuntu we are running and then use the correct sources list. 

It looks like we should pull in https://github.com/nir0s/distro since the standard library https://docs.python.org/3.5/library/platform.html#platform.linux_distribution is deprecated.

**Comment by murphm8** [comment]
We expect everything works, but would like to run some more tests before we officially mark Bionic as supported.

**Comment by ryanewel** [comment]
I tried running colcon bundle using ROS Melodic on Ubuntu Bionic and get the following exception:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/colcon_core/command.py", line 436, in verb_main
    rc = context.args.main(context=context)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/colcon_bundle/verb/bundle.py", line 122, in main
    context, path_context, upgrade_deps_graph)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/colcon_bundle/verb/bundle.py", line 149, in _manage_dependencies
    installers = self._setup_installers(context, path_context)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/colcon_bundle/verb/bundle.py", line 225, in _setup_installers
    installer.initialize(context)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/colcon_bundle/installer/apt.py", line 86, in initialize
    self.setup()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/colcon_bundle/installer/apt.py", line 120, in setup
    self._cache.update()
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 546, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:GPG error: http://packages.ros.org/ros/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5523BAEEB01FA116, E:The repository 'http://packages.ros.org/ros/ubuntu bionic InRelease' is not signed., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://us.archive.ubuntu.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32, E:The repository 'http://us.archive.ubuntu.com/ubuntu bionic InRelease' is not signed., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32, E:The repository 'http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease' is not signed., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32, E:The repository 'http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease' is not signed., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://us.archive.ubuntu.com/ubuntu bionic-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32, E:The repository 'http://us.archive.ubuntu.com/ubuntu bionic-security InRelease' is not signed., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://ports.ubuntu.com/ubuntu-ports bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32, E:The repository 'http://ports.ubuntu.com/ubuntu-ports bionic InRelease' is not signed., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32, E:The repository 'http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease' is not signed., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32, E:The repository 'http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease' is not signed., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32, E:The repository 'http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease' is not signed.
```

I had no other issues with using apt to install ros dependencies or installing melodic.

**Comment by shoemakerlevy9** [comment]
@murphm8 I'm using Ubuntu Bionic, ROS Melodic, colcon-bundle 0.0.13 and colcon-ros-bundle 0.3.6 and I get the same error as @ryanewel. 

Do I need to update colcon-bundle or colcon-ros-bundle in order for this to work on ubuntu bionic?

**Comment by murphm8** [comment]
@shoemakerlevy9  0.0.13 is the latest `colcon-bundle` release so you're good there.

`colcon-bundle` does not officially support running on Bionic, because of this issue that hasn't been addressed. I will sync up with the developer who added support for Gazebo 9 and Melodic on Monday to see what he did to work around this issue.

**Comment by murphm8** [comment]
@x77a1 Did you have to do any workarounds to get Bionic to work when you added the Melodic support?

**Comment by murphm8** [comment]
@x77a1 Got back to me. He had to add the following:

https://github.com/x77a1/colcon-bundle/blob/29fce72ed01ec42eadfb55bbccd4818350b6bd3f/colcon_bundle/installer/apt.py#L98-L101


@shoemakerlevy9 If you are running Bionic and want to be able to bundle now, I suggest using Docker. My normal workflows are inside Docker so I don't mess up my local environment.

I usually run something like: `docker run -it -v $(pwd):/workspace ros:kinetic bash` in my base workspace. This will mount the local directory to `/workspace` inside the container, and then I just execute commands like normal. I will look into adding the above snippet in the next release.

**Comment by shoemakerlevy9** [comment]
Since I'm developing on ubuntu 18.04 should I use `docker run -it -v $(pwd):/workspace ros:melodic bash`

**Comment by murphm8** [comment]
If your base OS is 18.04, but you want to use ROS Kinetic, then you should use the `ros:kinetic` image. The `ros:kinetic` image is 16.04 but is fully compatible with your base operating system through Docker.

**Comment by shoemakerlevy9** [comment]
@murphm8  Cool, I wasn't aware that docker allowed you to run ROS Kinetic on Ubuntu 18.04. Thats really good to know.

I'm trying to install colcon from source so that I can use x77a1's work around. I see you have notes in the readme about how to do this but I'm confused about what you mean by "pull down". Do you mean git clone, and is there an install script I have to run after doing that?

> To setup my workspace I generally pull down:
> 
> colcon-core (https://github.com/colcon/colcon-core.git)
> colcon-ros (https://github.com/colcon/colcon-ros.git)
> colcon-bundle (https://github.com/colcon/colcon-bundle)
> colcon-ros-bundle (https://github.com/colcon/colcon-ros-bundle)

**Comment by murphm8** [comment]
Ah, that stuff if for developing on the packages. If you want to install `colcon-bundle` from the branch I pushed you can use: 

`pip3 install git+https://github.com/colcon/colcon-bundle.git@apt_bug`. 

That should install it locally. `pip3` can be a little finicky, so you might want to `pip3 uninstall colcon-bundle` first.

**Comment by murphm8** [comment]
It looks like the issue is reproducible even with the suggested change: https://travis-ci.org/colcon/colcon-bundle/builds/517513003#L3735

**Comment by murphm8** [comment]
Referenced Manpage: https://manpages.debian.org/stretch/apt/apt-secure.8.en.html

It looks like a simple solution would be to provide a flag like `--apt-allow-insecure` that will set ` Acquire::AllowInsecureRepositories` to `True`

**Comment by shoemakerlevy9** [comment]
I'm having big problems with pip and pip3. I had my co-worker try on 16.04 and now he is having problems with pip and pip3 as well. 

I'm getting the following error when trying to run anything pip or pip3 related
`ModuleNotFoundError: No module named 'pip._internal'`

My co-worker is working off of Ubuntu 16.04 and is getting this error
`AssertionError: colcon-bundle .dist-info directory not found`

Both errors occur when trying to run
`pip3 install --user colcon-bundle colcon-ros-bundle`

**Comment by shoemakerlevy9** [comment]
@murphm8 Would it be possible for you to create a docker image with colcon and colcon-bundle installed and share with us. We still cannot get both installed correctly.

**Comment by murphm8** [comment]
@shoemakerlevy9  I'll add this to the docs too, it's a good idea to have an example. I can't really distribute an actual image as that has licensing implications, but here's an example Dockerfile you can use.

```
FROM ros:kinetic

RUN apt-get update && apt-get install -y python3-pip python3-apt

RUN pip3 install -U setuptools pip
RUN pip3 install colcon-ros-bundle
```

**Comment by murphm8** [comment]
With #79 merged I believe we can close this issue!
